

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labeldb?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: lcng
    password: password
    hikari:
      maximum-pool-size:100
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show_sql: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: update